name : Testing S3 actions

on:
  push:
    branches: 
      - main

jobs:
  Testing_s3_actions:
    name: Uploading objects into s3
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: listin files
        run: |
          pwd
          ls -l
      - name: uploading website files to s3 bucket
        run :  aws s3 sync /home/ubuntu/actions-runner/_work/website-code/website-code s3://devopsexpert.in --exclude '.git*' --exclude 'README.md'


      # - name: coping text file to s3 bucket
      #   run : aws s3 cp test.txt s3://devopsexpert.in
